version: '3.9'

services:
  

  db:
    image: mariadb:10.5.8
    restart: always
    ports: 
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: dorime
    container_name: mariadb_pastelitos

  adminer:
    image: adminer:4.8.0
    restart: always
    ports:
      - 8080:8080
    container_name: adminer_pastelitos

  php:
    build: .
    ports:
      - 9000:80
    volumes:
      - .:/var/www/html
      - ./conf/apache2:/etc/apache2
    restart: always
    container_name: php_pastelitos
